[package]
name = "clockwork"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
rand = "*"
serde = "*"
bincode = "*"
serde_derive = "*"

[dev-dependencies]
clap = "*"

