[package]
name = "renderer"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
gfx = "*"
gfx_window_glutin = "0.16.0"
gfx_device_gl = "*"
glutin = "0.8"
image = "*"

